name: now
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.7.16         # âœ… Firebase Messaging added
  url_launcher: ^6.2.5
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  intl: ^0.18.1
  nearby_connections: ^3.0.2
  flutter_sms: ^2.3.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true
